services:
  Shared.MongoConfig:
    factory:
      class: ./contexts/Recording/Shared/infrastructure/persistence/mongo/MongoConfigFactory
      method: 'createTestConfig'

  Shared.MongoClient:
    factory:
      class: ./contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['recording', '@Shared.MongoConfig']

  Shared.Logger:
    class: ./contexts/Shared/infrastructure/WinstonLogger
