services:
  Videos.VideoRepository:
    class: ./contexts/Recording/Videos/infrastructure/InMemoryVideoRepository

  Videos.VideoCreator:
    class: ./contexts/Recording/Videos/application/Create/VideoCreator
    arguments: ["@Videos.VideoRepository"]

  Videos.VideoFinder:
    class: ./contexts/Recording/Videos/application/Find/VideoFinder
    arguments: ["@Videos.VideoRepository"]
